[build.environment]
  NPM_FLAGS = "--prefix=/dev/null"
  NODE_VERSION = "14"
  PLAYWRIGHT_BROWSERS_PATH = "0"

[build]
  publish = "dist"
  command = "pnpm run build"

[[redirects]]
  from = "/2022/design-system/*"
  to = "/2022/design-system/index.html"
  status = 200

[[redirects]]
  from = "/2022/code-review/*"
  to = "/2022/code-review/index.html"
  status = 200

[[redirects]]
  from = "/2022/astro-introduce/*"
  to = "/2022/astro-introduce/index.html"
  status = 200

[[redirects]]
  from = "/"
  to = "https://nado1999.me/"
  status = 302